// PotatoPet.js - Character class inspired by POUPY classe_bixinho.py
class PotatoPet{constructor(canvas,ctx){this.canvas=canvas;this.ctx=ctx;this.x=canvas.width/2;this.y=canvas.height/2+50;this.baseSize=80;this.size=this.baseSize;this.targetSize=this.baseSize;this.hunger=100;this.happiness=100;this.cleanliness=100;this.maxStat=150;this.level=1;this.experience=0;this.maxExperience=100;this.state='IDLE';this.stateStartTime=Date.now();this.stateDuration=0;this.animationFrame=0;this.frameTimer=0;this.frameDelay=10;this.targetX=this.x;this.targetY=this.y;this.moveSpeed=0.5;this.lastStatDecay=Date.now();this.lastRandomMove=Date.now();this.birthTime=Date.now();this.totalSpins=0;this.unlockedAchievements=[];this.particles=[];this.bonusXPMultiplier=1;this.bonusXPEndTime=0;}
update(deltaTime){this.updateStats();this.updateMovement();this.updateAnimation(deltaTime);this.updateState();this.updateSize();this.updateParticles();}
updateStats(){const now=Date.now();const timeSinceLastDecay=(now-this.lastStatDecay)/1000;if(timeSinceLastDecay>=1){this.hunger=Math.max(0,this.hunger-5/30);this.happiness=Math.max(0,this.happiness-3/20);this.cleanliness=Math.max(0,this.cleanliness-2/60);this.lastStatDecay=now;if(this.hunger<=0||this.happiness<=0||this.cleanliness<=0){this.die();}}if(this.bonusXPMultiplier>1&&Date.now()>this.bonusXPEndTime){this.bonusXPMultiplier=1;}}
updateMovement(){const now=Date.now();if(now-this.lastRandomMove>5000&&this.state==='IDLE'){this.targetX=100+Math.random()*(this.canvas.width-200);this.targetY=200+Math.random()*(this.canvas.height-250);this.lastRandomMove=now;}const dx=this.targetX-this.x;const dy=this.targetY-this.y;const dist=Math.sqrt(dx*dx+dy*dy);if(dist>1){this.x+=(dx/dist)*this.moveSpeed;this.y+=(dy/dist)*this.moveSpeed;}}
updateAnimation(deltaTime){this.frameTimer++;if(this.frameTimer>=this.frameDelay){this.animationFrame=(this.animationFrame+1)%4;this.frameTimer=0;}}
updateState(){const now=Date.now();const elapsed=now-this.stateStartTime;if(this.state!=='IDLE'&&elapsed>this.stateDuration){this.setState('IDLE');}}
updateSize(){if(Math.abs(this.size-this.targetSize)>0.5){this.size+=(this.targetSize-this.size)*0.1;}}
updateParticles(){for(let i=this.particles.length-1;i>=0;i--){const p=this.particles[i];p.x+=p.vx;p.y+=p.vy;p.life--;if(p.life<=0){this.particles.splice(i,1);}}}
setState(newState){this.state=newState;this.stateStartTime=Date.now();switch(newState){case'EATING':this.stateDuration=2000;break;case'PLAYING':this.stateDuration=3000;break;case'CLEANING':this.stateDuration=2500;break;case'SLEEPING':this.stateDuration=3000;break;default:this.stateDuration=0;}}
applySpinResult(result){switch(result){case'FOOD':this.hunger=Math.min(this.maxStat,this.hunger+10);this.happiness=Math.max(0,this.happiness-2);this.setState('EATING');this.addExperience(10);this.createParticles('~D83C~DF74');break;case'PLAY':this.happiness=Math.min(this.maxStat,this.happiness+5);this.hunger=Math.max(0,this.hunger-3);this.setState('PLAYING');this.addExperience(10);this.createParticles('~D83C~DFA5');break;case'BATH':this.cleanliness=Math.min(this.maxStat,this.cleanliness+10);this.hunger=Math.max(0,this.hunger-5);this.setState('CLEANING');this.addExperience(10);this.createParticles('~F0~9F~9A~BF');break;case'SLEEP':this.hunger=Math.min(this.maxStat,this.hunger+5);this.happiness=Math.min(this.maxStat,this.happiness+5);this.cleanliness=Math.min(this.maxStat,this.cleanliness+5);this.setState('SLEEPING');this.addExperience(10);this.createParticles('~F0~9F~98~B4');break;case'BONUS':this.bonusXPMultiplier=2;this.bonusXPEndTime=Date.now()+10000;this.createParticles('~E2~9C~A8');break;case'FAIL':this.createParticles('~E2~9C~97');break;}this.totalSpins++;}
addExperience(amount){this.experience+=amount*this.bonusXPMultiplier;if(this.experience>=this.maxExperience){this.levelUp();}}
levelUp(){this.level++;this.experience=0;this.maxExperience=100*this.level;this.baseSize=80+(this.level*3);this.targetSize=this.baseSize;this.hunger=Math.min(this.maxStat,this.hunger+20);this.happiness=Math.min(this.maxStat,this.happiness+20);this.cleanliness=Math.min(this.maxStat,this.cleanliness+20);this.createLevelUpEffect();}
createParticles(emoji){for(let i=0;i<8;i++){const angle=(Math.PI*2*i)/8;this.particles.push({x:this.x,y:this.y,vx:Math.cos(angle)*2,vy:Math.sin(angle)*2,emoji:emoji,life:30});}}
createLevelUpEffect(){for(let i=0;i<16;i++){const angle=(Math.PI*2*i)/16;this.particles.push({x:this.x,y:this.y,vx:Math.cos(angle)*3,vy:Math.sin(angle)*3,emoji:'~E2~9C~A8',life:40});}}
render(){this.drawPotato();this.drawExpression();this.drawStateEffect();this.drawParticles();}
drawPotato(){const ctx=this.ctx;ctx.fillStyle='rgba(0, 0, 0, 0.2)';ctx.beginPath();ctx.ellipse(this.x,this.y+this.size*0.6,this.size*0.6,this.size*0.2,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=this.getPotatoColor();ctx.beginPath();ctx.ellipse(this.x,this.y,this.size*0.7,this.size,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='rgba(101, 67, 33, 0.3)';this.drawSpot(this.x-this.size*0.3,this.y-this.size*0.2,this.size*0.15);this.drawSpot(this.x+this.size*0.2,this.y+this.size*0.3,this.size*0.12);this.drawSpot(this.x-this.size*0.1,this.y+this.size*0.5,this.size*0.1);}
drawSpot(x,y,radius){this.ctx.beginPath();this.ctx.arc(x,y,radius,0,Math.PI*2);this.ctx.fill();}
getPotatoColor(){const avgStat=(this.hunger+this.happiness+this.cleanliness)/3;if(avgStat>100){return'#D4A574';}else if(avgStat>50){return'#B8956A';}else{return'#8B7355';}}
drawExpression(){const ctx=this.ctx;const emotion=this.getEmotion();ctx.fillStyle='#000';if(emotion==='happy'){this.drawHappyEyes();this.drawHappyMouth();}else if(emotion==='sad'){this.drawSadEyes();this.drawSadMouth();}else if(emotion==='sleeping'){this.drawSleepingEyes();}else{this.drawNeutralEyes();this.drawNeutralMouth();}}
getEmotion(){if(this.state==='SLEEPING')return'sleeping';const avgStat=(this.hunger+this.happiness+this.cleanliness)/3;if(avgStat>100)return'happy';if(avgStat>50)return'neutral';return'sad';}
drawHappyEyes(){const ctx=this.ctx;const eyeY=this.y-this.size*0.2;ctx.beginPath();ctx.arc(this.x-this.size*0.25,eyeY,this.size*0.08,0.2,Math.PI-0.2);ctx.lineWidth=3;ctx.stroke();ctx.beginPath();ctx.arc(this.x+this.size*0.25,eyeY,this.size*0.08,0.2,Math.PI-0.2);ctx.stroke();}
drawHappyMouth(){const ctx=this.ctx;ctx.beginPath();ctx.arc(this.x,this.y+this.size*0.1,this.size*0.3,0,Math.PI);ctx.lineWidth=3;ctx.stroke();}
drawSadEyes(){const ctx=this.ctx;const eyeY=this.y-this.size*0.2;ctx.beginPath();ctx.arc(this.x-this.size*0.25,eyeY,this.size*0.08,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(this.x+this.size*0.25,eyeY,this.size*0.08,0,Math.PI*2);ctx.fill();}
drawSadMouth(){const ctx=this.ctx;ctx.beginPath();ctx.arc(this.x,this.y+this.size*0.3,this.size*0.25,Math.PI,0);ctx.lineWidth=3;ctx.stroke();}
drawSleepingEyes(){const ctx=this.ctx;const eyeY=this.y-this.size*0.2;ctx.beginPath();ctx.moveTo(this.x-this.size*0.35,eyeY);ctx.lineTo(this.x-this.size*0.15,eyeY);ctx.lineWidth=3;ctx.stroke();ctx.beginPath();ctx.moveTo(this.x+this.size*0.15,eyeY);ctx.lineTo(this.x+this.size*0.35,eyeY);ctx.stroke();}
drawNeutralEyes(){const ctx=this.ctx;const eyeY=this.y-this.size*0.2;ctx.beginPath();ctx.arc(this.x-this.size*0.25,eyeY,this.size*0.08,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.arc(this.x+this.size*0.25,eyeY,this.size*0.08,0,Math.PI*2);ctx.fill();}
drawNeutralMouth(){const ctx=this.ctx;ctx.beginPath();ctx.moveTo(this.x-this.size*0.2,this.y+this.size*0.2);ctx.lineTo(this.x+this.size*0.2,this.y+this.size*0.2);ctx.lineWidth=3;ctx.stroke();}
drawStateEffect(){const ctx=this.ctx;if(this.state==='EATING'){ctx.font='30px Arial';ctx.fillText('~D83C~DF74',this.x+this.size*0.5,this.y-this.size*0.5);}else if(this.state==='PLAYING'){ctx.font='30px Arial';ctx.fillText('~D83C~DFA5',this.x+this.size*0.5,this.y-this.size*0.5);}else if(this.state==='CLEANING'){ctx.font='30px Arial';ctx.fillText('~F0~9F~9A~BF',this.x+this.size*0.5,this.y-this.size*0.5);}else if(this.state==='SLEEPING'){ctx.font='25px Arial';const bounce=Math.sin(Date.now()/500)*5;ctx.fillText('Zzz',this.x+this.size*0.6,this.y-this.size*1.2+bounce);}if(this.bonusXPMultiplier>1){ctx.font='20px Arial';ctx.fillStyle='#FFD700';ctx.fillText('2X XP!',this.x-30,this.y-this.size*1.2);}}
drawParticles(){const ctx=this.ctx;ctx.font='20px Arial';for(const p of this.particles){ctx.globalAlpha=p.life/30;ctx.fillText(p.emoji,p.x,p.y);}ctx.globalAlpha=1;}
die(){alert('Potato has died!');SaveManager.clear();location.reload();}
getAge(){const ageMs=Date.now()-this.birthTime;const ageDays=Math.floor(ageMs/(1000*60*60*24));const ageHours=Math.floor((ageMs%(1000*60*60*24))/(1000*60*60));if(ageDays>0){return`${ageDays} days`;}else if(ageHours>0){return`${ageHours} hours`;}else{return'Less than an hour';}}}
